# Site settings
title: lazydogez的博客 # 你的博客名字，可以定义修订
header-img: "img/azurelane.png"
tagline: "cn"  
description: "这是lazydogez的博客"  # 一句话描述你的博客
baseurl: ""
url: "https://lazydogez.github.io"  # 此处填写你的博客地址 

# About/contact
owner: 
  name: "lazydogez" # 填写作者信息：名字
  email: ustcyanzhe@gmail.com # 填写作者信息：邮箱
  bio: "老博士随便写写" # 填写作者信息：博客描述

# Data
gavatar: img/favicon.png # 浏览器地址栏小图标，可自定义更改
favicon: img/favicon.png # 浏览器地址栏小图标，可自定义更改

# douban_username:  # 你的豆瓣id
# twitter_username: 
# github_username: 
# facebook_username: 
# weibo_username: 
# zhihu_username: 

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: America/New_York

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "lazydogez" # 你的名字
      header-img: "img/azurelane.png" # We don't want posts without a header image, that whould mean white on white

# Comments 
#comments :
  # provider : disqus # 使用 disqus 评论模块，读者翻墙才能看见
  # duoshuo :
   # short_name :  # 填写你的 disqus id
  #disqus :
      #short_name :   # 填写你的 disqus id

# Analytics and webmaster tools stuff goes here
google_analytics: 288688712  # 填写你  google_analytics id
#google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
#bing_verify:

# Links to include in footer navigation
